//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_ar_galima_receiver.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_galima_tag_sight.smd"
	blank
	blank
}

$bodygroup "laser"
{
	blank
	studio "meshes/attachment_vm_ar_galima_tag_laser.smd"
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_ar_galima_stock_adapter.smd"
}