//MESHES


$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$scale 0.3937
$bodygroup "receiver"
{
	studio "meshes/attachment_vm_pi_cpapa_receiver.smd"
}

$bodygroup "mag"
{
	blank
	studio "meshes/attachment_vm_pi_cpapa_mag.smd"
}


$bodygroup "tag_rail"
{
	blank
	studio "meshes/attachment_vm_pi_cpapa_rail.smd"
}

$scale 1
$bodygroup "sight"
{
	studio "meshes/attachment_vm_pi_cpapa_sight_on.smd"
	blank
}