//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "1"
{
	blank
	studio "meshes/attachment_vm_sm_mpapa5_receiver.smd"
}

$bodygroup "2"
{
	blank
	studio "meshes/attachment_vm_sm_mpapa5_tag_bsight.smd"
}

$bodygroup "3"
{
	blank
	studio "meshes/attachment_vm_sm_mpapa5_laser_attach.smd"
}

$bodygroup "4"
{
	blank
	studio "meshes/attachment_vm_sm_mpapa5_rail.smd"
}

$bodygroup "5"
{
	blank
	studio "meshes/attachment_vm_sm_mpapa5_stock_adapter.smd"
}
