//MESHES

$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_ar_scharlie_receiver.smd"
	blank
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_scharlie_tag_back_sight_on.smd"
	studio "meshes/attachment_vm_ar_scharlie_tag_back_sight_off.smd"
	blank
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_ar_scharlie_stock_adapter.smd"
}