//MESHES

$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "worldmodel"
{
	studio "meshes/w_scharlie.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_scharlie_tag_back_sight_on.smd"
	studio "meshes/attachment_vm_ar_scharlie_tag_back_sight_off.smd"
	blank
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_ar_scharlie_stock_adapter.smd"
}


$collisionmodel "meshes/w_scharlie.smd"