// Created by Crowbar 0.55

$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/attachment_vm_hybrid_west03_hide.mdl"

// Meshes
$bodygroup "hide"
{
	studio "attachment_vm_hybrid_west03_hide.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\attachments\"
$cdmaterials ""

// Sequences
$sequence "reference" {
	"attachment_vm_hybrid_west03_hide.smd"
	loop
}