// Created by Crowbar 0.55
$scale 0.3937
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "attachment_vm_pi_cpapa_grip.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_pi_cpapa_grip.smd"
}

$collisionmodel "attachment_vm_pi_cpapa_grip"

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\357\"

$scale 0.3937
// Sequences
$sequence "reference" {
	"attachment_vm_pi_cpapa_grip.smd"
	loop
}