// Created by Crowbar 0.55
$maxverts 999999

$illumposition 0 0 0

$modelname "viper/mwii/weapons/w_fnov2000.mdl"

// Meshes
$include meshes_worldmodel.qc

// Weapon Bones
$include bones_weapon_worldmodel.qc

// Attachments
$include attachments_worldmodel.qc

$surfaceprop "weapon"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\mwii\weapons\fnov2000\"

$sequence "reference" {
	"meshes/wm_ar_fnov2000.dmx"
}
