// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/attachment_vm_pi_papa320_receiver_v13.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_pi_papa320_receiver_v13.smd"
}


$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\p320\"

// Sequences
$sequence "reference" {
	"attachment_vm_pi_papa320_receiver_v13.smd"
	loop
}