// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/charlie9/attachment_vm_sm_charlie9_xmag.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_sm_charlie9_xmag.smd"
}

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\MW\weapons\charlie9\"

// Sequences
$sequence "reference" {
	"attachment_vm_sm_charlie9_xmag.smd"
	loop
}