// Created by Crowbar 0.55
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/cw/rigs/gloves/mp_western_vm_gloves_t9price_1_1.mdl"

// Meshes
$bodygroup "gloves"
{
	studio "mp_western_vm_gloves_t9price_1_1.smd"
}


$include mw_bonemerge.qci

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\CW\rigs\gloves\t9_price\"


// Sequences
$sequence "Idle" {
	"mp_western_vm_gloves_t9price_1_1.smd"
}