//WEAPON BONES

$definebone "ValveBiped.Anim_Attachment_RH" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_sling" "ValveBiped.Anim_Attachment_RH" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "tag_ik_loc_ri"
$bonemerge "tag_ik_loc_le"
$bonemerge "tag_acog_2"
$bonemerge "tag_reflex"
$bonemerge "tag_thermal"
$bonemerge "tag_holo"
$bonemerge "tag_scope"
$bonemerge "tag_silencer"
$bonemerge "tag_laser_attach"
$bonemerge "tag_sight_on"
$bonemerge "tag_sight_off"