// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/papa90/attachment_vm_sm_papa90_mag_v4.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_sm_papa90_mag_v4.smd"
}

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\MW\weapons\papa90\"

// Sequences
$sequence "reference" {
	"attachment_vm_sm_papa90_mag_v4.smd"
	loop
}