//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_sn_crossbow_receiver.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_sn_crossbow_sight_on.smd"
	blank
        blank
}

$bodygroup "tag_grip_hide"
{
	studio "meshes/attachment_vm_sn_crossbow_grip_hide.smd"
        studio "meshes/attachment_vm_sn_crossbow_grip_show.smd"
        blank
}