//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_lm_kilo121_receiver.smd"
}

$bodygroup "sight"
{
	studio "meshes/attachment_vm_lm_kilo121_sight_on.smd"
	studio "meshes/attachment_vm_lm_kilo121_sight_off.smd"
	blank
}

$bodygroup "tag_grip_hide"
{
	studio "meshes/attachment_vm_lm_kilo121_grip_hide.smd"
	blank
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_lm_kilo121_stock_adapter.smd"
}