//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "reference"
{
	blank
	studio "meshes/attachment_weapon_vm_sn_hdromeo_receiver.smd"
}

$bodygroup "reference2"
{
	blank
	studio "meshes/attachment_weapon_vm_sn_hdromeo_receiver_sight.smd"
}

$bodygroup "tag_stock"
{
	studio "meshes/attachment_weapon_vm_sn_hdromeo_pgrip.smd"
	studio "meshes/attachment_weapon_vm_sn_hdromeo_receiver_stock.smd"
}

