//MESHES
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/w_beta.smd"
}

$bodygroup "tag_laser"
{
	blank
	studio "meshes/attachment_vm_sm_beta_tag_laser.smd"
}

$bodygroup "tag_rail"
{
	blank
	studio "meshes/attachment_vm_sm_beta_tag_rail.smd"
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_sm_beta_tag_stock_adapter.smd"
}



$collisionmodel "meshes/w_beta.smd"