// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/augolf/attachment_vm_sm_augolf_smg_xmag.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_sm_augolf_smg_xmag.smd"
}

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\MW\weapons\augolf\"
$cdmaterials "viper\MW\weapons\uzulu\"

// Sequences
$sequence "reference" {
	"attachment_vm_sm_augolf_smg_xmag.smd"
	loop
}