//WEAPON BONES

$definebone "tag_pistol_offset" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_pistol_offset" "tag_weapon" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "tag_barrel_attach"
$bonemerge "tag_mag_attach"
$bonemerge "tag_stock_attach"
$bonemerge "j_mag1"
$bonemerge "j_b_loader"
$bonemerge "j_b_loader_top"
$bonemerge "j_b_loader_01"
$bonemerge "j_b_loader_02"
$bonemerge "j_b_loader_03"
$bonemerge "j_b_loader_04"
$bonemerge "j_b_loader_05"
$bonemerge "j_b_loader_06"