//MESHES

$scale 0.3937
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/w_357.smd"
	blank
}

$scale 1

$bodygroup "pgrip"
{
	studio "meshes/attachment_vm_pi_cpapa_pgrip.smd"
	blank
}


$bodygroup "tag_rail"
{
	blank
	studio "meshes/attachment_vm_pi_cpapa_rail.smd"
}

$bodygroup "sight"
{
	studio "meshes/attachment_vm_pi_cpapa_sight_on.smd"
	blank
}

$scale 0.3937
$collisionmodel "meshes/w_357.smd"