//MESHES

$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "worldmodel"
{
	studio "meshes/w_lima86.smd"
}

$bodygroup "sight"
{
	studio "meshes/attachment_vm_lm_lima86_sight.smd"
	blank
	blank
}

$bodygroup "tag_stock"
{
	studio "meshes/attachment_vm_lm_lima86_stock.smd"
	blank
}

$bodygroup "laser"
{
	blank
	studio "meshes/attachment_vm_lm_lima86_laser.smd"
}
$collisionmodel "meshes/w_lima86.smd"