//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_lm_lima86_receiver.smd"
	blank
}

$bodygroup "sight"
{
	studio "meshes/attachment_vm_lm_lima86_sight.smd"
	blank
	blank
}

$bodygroup "tag_stock"
{
	studio "meshes/attachment_vm_lm_lima86_stock.smd"
	blank
}

$bodygroup "laser"
{
	blank
	studio "meshes/attachment_vm_lm_lima86_laser.smd"
}