//WEAPON BONES

$definebone "ValveBiped.Anim_Attachment_RH" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_pistol_offset" "ValveBiped.Anim_Attachment_RH" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "tag_barrel_attach"
$bonemerge "j_slide"
$bonemerge "j_bullet_01"
$bonemerge "j_bullet_02"
$bonemerge "j_bullet_03"
$bonemerge "j_bullet_04"
$bonemerge "j_barrel"
$bonemerge "tag_mag_attach"
$bonemerge "j_mag1"
$bonemerge "j_mag2"
$bonemerge "tag_stock_attach"
$bonemerge "tag_laser_attach"