// Created by Crowbar 0.55
$scale 1
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/sierra552/attachment_vm_ar_sierra552_stockno.mdl"


// Meshes
$bodygroup "slide"
{
	studio "attachment_vm_ar_sierra552_stockno.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\sierra552\"

$bonemerge "tag_lightstock_attach"



$scale 0.3937
// Sequences
$sequence "reference" {
	"attachment_vm_ar_sierra552_stockno.smd"
	loop
}