// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/akilo47/attachment_vm_ar_akilo47_xmags_v21.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_ar_akilo47_xmags_v21.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\akilo47\"
$cdmaterials "viper\MW\attachments\"

// Sequences
$sequence "reference" {
	"attachment_vm_ar_akilo47_xmags_v21.smd"
	loop
}