// Created by Crowbar 0.55 fuck off
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/akilo47/attachment_vm_bayonet_akilo47.mdl"


// Meshes
$bodygroup "bipod"
{
	studio "attachment_vm_bayonet_akilo47.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\akilo47\"

// Sequences
$sequence "reference" {
	"attachment_vm_bayonet_akilo47.smd"
	loop
}