// Created by Crowbar 0.55
$maxverts 999999

$illumposition 0 0 0

$modelname "viper/vanguard/weapons/w_sindigi510.mdl"

// Meshes
$include meshes_worldmodel.qc

// Weapon Bones
$include bones_weapon_worldmodel.qc

// Attachments
$include attachments_worldmodel.qc

$surfaceprop "weapon"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\vanguard\weapons\sindigo510\"

$sequence "reference" {
	"meshes/w_sindigo510.smd"
}
