//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_sn_mike14_receiver.smd"
}

$bodygroup "laser"
{
	blank
	studio "meshes/attachment_vm_sn_mike14_tag_laser.smd"
}

$bodygroup "tag_stock"
{
	studio "meshes/attachment_vm_sn_mike14_stock.smd"
	studio "meshes/attachment_vm_sn_mike14_stock_v2_alt.smd"
	studio "meshes/attachment_vm_sn_mike14_stock_v3.smd"
	studio "meshes/attachment_vm_sn_mike14_stock_v3_alt.smd"
}