//MESHES

$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/w_tango21.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_tango21_tag_sight_on_1.smd"
	studio "meshes/attachment_vm_ar_tango21_tag_sight_off_1.smd"
	blank
}

$bodygroup "tag_barrel_hide"
{
	studio "meshes/attachment_vm_ar_tango21_grip_hide.smd"
	blank
}

$collisionmodel "meshes/w_tango21.smd"