// Created by Crowbar 0.55
$illumposition 0 0 0
$scale 0.3937
$origin 0 0 0 -90

$modelname "attachment_vm_ar_falpha_stock_tactical_v1.mdl"


// Meshes
$bodygroup "slide"
{
	studio "attachment_vm_ar_falpha_stock_tactical_v1.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\falpha\"

$bonemerge "tag_stock_attach"


// Sequences
$sequence "reference" {
	"attachment_vm_ar_falpha_stock_tactical_v1.smd"
	loop
}