// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/smgolf45/attachment_vm_sm_smgolf45_mag_v2.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_sm_smgolf45_mag_v2.smd"
}

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\MW\weapons\smgolf45\"

// Sequences
$sequence "reference" {
	"attachment_vm_sm_smgolf45_mag_v2.smd"
	loop
}