//WEAPON BONES

$definebone "ValveBiped.Bip01_R_Hand" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_sling" "ValveBiped.Bip01_R_Hand" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "tag_barrel_attach"
$bonemerge "tag_mag_attach"
$bonemerge "tag_stock_attach"
$bonemerge "tag_reflex"
$bonemerge "tag_holo"
$bonemerge "tag_thermal"
$bonemerge "tag_acog_2"
$bonemerge "tag_hybrid"
$bonemerge "tag_scope"
$bonemerge "tag_ik_loc_le"
$bonemerge "tag_ik_loc_ri"
$bonemerge "tag_laser_attach"
$bonemerge "j_barrel"