$maxverts "99999999"
$modelname "viper/vg/attachments/vm_m1golf_barrel_hv_xl_00.mdl"
$cdmaterials "viper/vg/weapons/m1golf/"
$scale 1
$body "vm_m1golf_barrel_hv_xl_00_reference.smd" "vm_m1golf_barrel_hv_xl_00.smd"
$sequence "vm_m1golf_barrel_hv_xl_00" "vm_m1golf_barrel_hv_xl_00.smd"

$attachment "muzzle" "tag_flash_attachment" 0.00 0.00 0 rotate -0 0 0
$attachment "silencer" "tag_silencer" 0.00 0.00 0 rotate -0 0 0