// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/mpapa5/attachment_vm_sm_mpapa5_mag.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_sm_mpapa5_mag.smd"
}

$surfaceprop "default"
$contents "solid"

// Materials
$cdmaterials "viper\MW\weapons\mpapa5\"
$cdmaterials "viper\MW\weapons\uzulu\"

// Sequences
$sequence "reference" {
	"attachment_vm_sm_mpapa5_mag.smd"
	loop
}