// Created by Crowbar 0.55
$maxverts 999999

$illumposition 0 0 0

$modelname "w_g3a3.mdl"

// Meshes
$include meshes_worldmodel.qc

// Weapon Bones
$include bones_weapon_worldmodel.qc

// Attachments
$include attachments_worldmodel.qc

$surfaceprop "weapon"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\g3a3\"

$sequence "reference" {
	"meshes/w_custom_g3a3_skm_1p_g3a3_edit.smd"
}
