//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_sm_victor_receiver.smd"
}


$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_sm_victor_tag_stock_attach.smd"
}

$bodygroup "tag_laser"
{
	blank
	studio "meshes/attachment_vm_sm_victor_tag_laser_attach.smd"
}

$bodygroup "sight"
{
	studio "meshes/attachment_vm_sm_victor_tag_sight_on.smd"
	studio "meshes/attachment_vm_sm_victor_tag_sight_off.smd"
	blank
}