//MESHES

$scale 0.3937
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "worldmodel"
{
	studio "meshes/w_kilo.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_kilo433_tag_sight_on.smd"
	studio "meshes/attachment_vm_ar_kilo433_tag_sight_off.smd"
}

$bodygroup "rails"
{
	blank
	studio "meshes/attachment_vm_ar_kilo433_barrel_rails.smd"
}

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_ar_kilo433_stock_adapter.smd"
}


$collisionmodel "meshes/w_kilo.smd"