//MESHES

$scale 1
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	blank
	studio "meshes/attachment_vm_ar_mcharlie_receiver.smd"
}

// $bodygroup "tag_sight"
// {
// 	studio "meshes/attachment_vm_ar_mcharlie_tag_sight_on.smd"
// 	studio "meshes/attachment_vm_ar_mcharlie_tag_sight_off.smd"
// 	blank
// }

$bodygroup "tag_stock"
{
	blank
	studio "meshes/attachment_vm_ar_mcharlie_stock_adapter.smd"
}
