// Created by Crowbar 0.55

$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/mike4/attachment_vm_ar_mike4_stock_v27.mdl"


// Meshes
$bodygroup "slide"
{
	studio "attachment_vm_ar_mike4_stock_v27.smd"
}

$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\mike4\"


// Sequences
$sequence "reference" {
	"attachment_vm_ar_mike4_stock_v27.smd"
	loop
}