//MESHES
$maxverts 9999999
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "receiver"
{
	studio "meshes/attachment_vm_ar_valpha_receiver.smd"
}

$bodygroup "tag_rail"
{
	blank
	studio "meshes/attachment_vm_ar_valpha_rail.smd"
}

$bodygroup "tag_sight"
{
	studio "meshes/attachment_vm_ar_valpha_tag_sight_barrel_1.smd"
	blank
}

$bodygroup "tag_grip"
{
	studio "meshes/attachment_vm_ar_valpha_stock_hide.smd"
	blank
}