//MESHES

$scale 0.3937
$illumposition 0 0 0

$origin 0 0 0 -90

$bodygroup "worldmodel"
{
	blank
	studio "meshes/w_falima.smd"
}

// $bodygroup "tag_sight"
// {
// 	studio "meshes/attachment_vm_ar_falima_tag_sight_on.smd"
// 	studio "meshes/attachment_vm_ar_falima_tag_sight_off.smd"
// 	blank
// }

// $bodygroup "tag_stock"
// {
// 	blank
// 	studio "meshes/attachment_vm_ar_falima_stock_adapter.smd"
// }


$collisionmodel "meshes/w_falima.smd"