// Created by Crowbar 0.55

$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/attachment_vm_ar_kilo433_stock_v2.mdl"


// Meshes
$bodygroup "slide"
{
	studio "attachment_vm_ar_kilo433_stock_v2.smd"
}


$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\kilo433\"

$bonemerge "tag_stock_attach"




// Sequences
$sequence "reference" {
	"attachment_vm_ar_kilo433_stock_v2.smd"
	loop
}