//WEAPON BONES

$definebone "ValveBiped.Anim_Attachment_RH" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_pistol_offset" "ValveBiped.Anim_Attachment_RH" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "tag_silencer" "tag_pistol_offset" 5.55 0.00 1.05 0 0 0 0 0 0 0 0 0

$bonemerge "tag_barrel_attach"
$bonemerge "tag_mag_attach"
$bonemerge "tag_stock_attach"
$bonemerge "tag_silencer"
$bonemerge "tag_reflex"
$bonemerge "tag_scope"
$bonemerge "tag_folding_grip"