// Created by Crowbar 0.55
$illumposition 0 0 0

$origin 0 0 0 -90

$modelname "viper/mw/attachments/attachment_vm_pi_mike1911_v21_receiver.mdl"


// Meshes
$bodygroup "grip"
{
	studio "attachment_vm_pi_mike1911_v21_receiver.smd"
}


$surfaceprop "default"
$contents "solid"
$mostlyopaque

// Materials
$cdmaterials "viper\MW\weapons\m1911\"

// Sequences
$sequence "reference" {
	"attachment_vm_pi_mike1911_v21_receiver.smd"
	loop
}